#spring.data.mongodb.database=${env.MONGO_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USERNAME}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
#spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USERNAME}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}.mongodb.net/${env.MONGO_DATABASE}?retryWrites=true&w=majority&readPreference=secondaryPreferred
accessTokenExpirationMinutes: 5
refreshTokenExpirationDays: 30
accessTokenSecret: 12345
refreshTokenSecret: 54321

spring:
#  elasticsearch:
#    uris: https://localhost:9200
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      use-redis-cache: true
    mongodb:
      uri: mongodb://localhost:27017/foreveread
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/better_read
    username: root
    password: 1111
#    password: mtm172004
  jpa:
    hibernate: ddl-auto=update
logging:
  level:
    dbmsforeveread:
      foreveread: DEBUG

#xpack:
#  security:
#    enabled: false
#spring.security.oauth2.client.registration.github.client-id=: GITHUB_CLIENT_ID
#spring.security.oauth2.client.registration.github.client-secret= GITHUB_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.client-id=: GITHUB_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret= GITHUB_CLIENT_SECRET
#spring.security.user.name=user
#spring.security.user.password='{bcrypt}$2a$10$z2N9NQ82z655FQfOeoN5xOPT7C0mcjuxh1H47nqqS9vWONlyutpQi'

#logging.level.org.springframework.security=TRACE