accessTokenExpirationMinutes: 5
refreshTokenExpirationDays: 30
accessTokenSecret: 12345
refreshTokenSecret: 54321

spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      use-redis-cache: true
    mongodb:
      uri: mongodb://localhost:27017/foreveread
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/better_read
    username: root
    password: ${env.MYSQL_PASSWORD}
  #    password: 123456
  jpa:
    hibernate: ddl-auto=update
  neo4j:
    uri: ${env.AURA_URI}
    authentication:
      username: ${env.AURA_USER}
      password: ${env.AURA_PASSWORD}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    dbmsforeveread:
      foreveread: DEBUG
    org:
      springframework:
        web: DEBUG
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: better_read
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer:org.apache.kafka.common.serialization.StringSerializer
      value-serializer:org.apache.kafka.common.serialization.StringSerializer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true